-- ═══════════════════════════════════════════════════════════════
-- ABHAY OYUN - SEED DATA
-- Run this AFTER running schema.sql in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- EVENTS
INSERT INTO events (title, slug, short_description, description, event_type, category, start_date, end_date, location_name, location_city, location_country, is_online, max_participants, spots_remaining, price_amount, price_currency, status, is_featured, is_spot_limited, spot_threshold, hero_image) VALUES
('Ancestral Fire Retreat 2026', 'ancestral-fire-retreat-2026', 'A 7-day immersive journey into the heart of Siberian shamanic traditions', 'Deep in the Altai Mountains, where the spirits of the ancestors still speak through the wind, we gather for seven days of profound transformation. Each day begins with dawn ceremony at the sacred fire, followed by intensive shamanic teachings, drum journeys, and plant medicine work. Evenings are spent in council around the fire, sharing stories and receiving direct transmissions from Shaman Abhay.', 'retreat', 'retreat', '2026-06-14', '2026-06-21', 'Altai Mountains Base Camp', 'Gorno-Altaysk', 'Russia', false, 8, 3, 2800.00, 'USD', 'published', true, true, 5, '/shaman_birch_forest.png'),
('Opening the Ancestral Channel', 'opening-ancestral-channel', 'A 3-hour group ceremony to connect with your lineage and release inherited patterns', 'In this sacred online gathering, Shaman Abhay opens the ancestral channel for all participants. Through guided drum journey, energy transmission, and group healing work, you will connect with your lineage, receive messages from your ancestors, and release patterns that no longer serve you. This ceremony has been a gateway for thousands to begin their shamanic healing journey.', 'ceremony', 'ceremony', '2026-05-31', NULL, 'Online via Zoom', 'Online', 'Worldwide', true, 20, 5, 150.00, 'USD', 'published', true, true, 5, '/yurt_fire_healing.png'),
('Shamanic Training Level 1', 'shamanic-training-level-1-2026', 'The foundational training for those called to walk the shamanic path', 'An intensive 7-day residential training in Sintra, Portugal. This is the first level of the SAMPO shamanic training system. You will learn the foundational techniques of shamanic journeying, energy protection, soul retrieval basics, drum making, and ceremonial leadership. Graduates leave equipped to begin their own practice and continue to Level 2.', 'training', 'training', '2026-08-01', '2026-08-07', 'Quinta da Lua', 'Sintra', 'Portugal', false, 12, 8, 1800.00, 'USD', 'published', true, true, 5, '/drum_gold_waves.png'),
('Divination & Oracle Workshop', 'divination-oracle-workshop-2026', 'Learn the art of reading the unseen through Siberian rune traditions', 'A full-day workshop in Berlin exploring the ancient Siberian art of divination. You will learn to work with the sacred runes of the Altai tradition, interpret signs in nature, read energy fields, and develop your intuitive abilities. Practical exercises, group readings, and individual guidance from Abhay.', 'workshop', 'workshop', '2026-07-20', NULL, 'Berlin Shamanic Center', 'Berlin', 'Germany', false, 10, 7, 300.00, 'USD', 'published', false, true, 5, '/sacred-geometry.png'),
('Soul Retrieval Intensive', 'soul-retrieval-intensive-2026', 'A full-day workshop exploring the art of soul retrieval and fragments recovery', 'Soul loss is one of the primary causes of depression, chronic fatigue, and the feeling that something is missing. In this intensive workshop, you will learn to identify soul loss, understand the shamanic map of the soul, and practice safe soul retrieval techniques. Includes a group soul retrieval ceremony.', 'workshop', 'workshop', '2026-07-05', NULL, 'Amsterdam Healing Center', 'Amsterdam', 'Netherlands', false, 12, 12, 400.00, 'USD', 'published', false, false, 5, '/healing-global-harmony.jpg'),
('Plant Medicine Integration Circle', 'plant-medicine-integration-june', 'Monthly circle for those who have worked with plant medicines', 'A safe, held space for those navigating the integration journey after plant medicine experiences. Each circle includes grounding practices, sharing circle, energy healing, and guided integration techniques. Open to all who have worked with plant medicines in a ceremonial context, regardless of tradition.', 'ceremony', 'ceremony', '2026-06-15', NULL, 'Online via Zoom', 'Online', 'Worldwide', true, 25, 15, 75.00, 'USD', 'published', false, false, 5, '/shaman_fire.png'),
('Women''s Shamanic Gathering', 'womens-shamanic-gathering-2026', 'A sacred weekend of sisterhood, ceremony, and ancestral healing', 'An intimate gathering for women to reconnect with their ancient feminine power. Through moon ceremonies, sisterhood circles, drum healing, and forest rituals, you will remember the wild wisdom that lives in your bones. Limited to 12 women to ensure deep, personal work.', 'retreat', 'retreat', '2026-09-10', '2026-09-13', 'Sacred Valley', 'Lizbon', 'Portugal', false, 12, 9, 890.00, 'USD', 'published', true, true, 5, '/sao-gallery-img1.jpg'),
('Men''s Power Intensive', 'mens-power-intensive-2026', 'Reclaim your masculine power through fire, drum, and ceremony', 'A 5-day immersive for men ready to step fully into their energetic sovereignty. Cold exposure, sacred fire ceremony, drum healing, and direct shamanic mentorship with Master Abhay. This is not a workshop — it is an initiation.', 'retreat', 'retreat', '2026-10-05', '2026-10-10', 'Colorado Mountain Retreat', 'Denver', 'United States', false, 18, 14, 1200.00, 'USD', 'published', true, true, 5, '/sao-gallery-img3.jpg');

-- TESTIMONIALS
INSERT INTO testimonials (client_name, client_location, client_image, content, short_quote, service_type, rating, is_featured, display_order) VALUES
('Maria K.', 'Berlin, Germany', '/sao-gallery-img5.jpg', 'After one session with Abhay, I felt a weight lift from my chest that I had been carrying for 20 years. It was like my cells remembered how to breathe again. I had tried therapy, meditation, every modality I could find — but nothing reached the depth that this work did. The session was both gentle and incredibly powerful.', 'My cells remembered how to breathe again.', 'Healing Session', 5, true, 1),
('James R.', 'London, UK', '/sao-gallery-img3.jpg', 'The SAMPO System completely rewired how I experience stress. What used to cripple me now passes through me. I have never felt more sovereign in my own body. After years of anxiety and burnout, I finally have tools that actually work. This is not coping — this is transformation.', 'What used to cripple me now passes through me.', 'Training Program', 5, true, 2),
('Elena V.', 'Moscow, Russia', '/sao-gallery-img7.jpg', 'I traveled to three continents seeking healing. What Abhay achieved in a single masterclass surpassed everything. This is ancient wisdom in its purest form, delivered with remarkable precision and compassion. The shift was immediate and lasting.', 'This is ancient wisdom in its purest form.', 'Masterclass', 5, true, 3),
('Priya S.', 'Mumbai, India', '/sao-gallery-img8.jpg', 'What people remember most after a personal encounter with the shaman is the special inner feeling — an all-embracing love that truly touches the heart. I felt seen at a level I did not know was possible. The ceremony continues to unfold in my life weeks later.', 'An all-embracing love that truly touches the heart.', 'Ceremony', 5, false, 4),
('David M.', 'New York, USA', NULL, 'I came to the Ancestral Fire Retreat skeptical and left transformed. The fire ceremonies, the drumming, the direct transmissions from Abhay — everything was authentic and powerful. I have been on a spiritual path for 20 years and this was unlike anything I have experienced.', 'The most authentic ceremony I have ever attended.', 'Retreat', 5, true, 5),
('Sophie L.', 'Paris, France', NULL, 'Working with Abhay helped me understand the root causes of patterns I had struggled with for years. His approach is both deeply traditional and accessible to modern seekers. The private session was worth more than years of therapy.', 'Deeply traditional yet accessible to modern seekers.', 'Private Session', 5, false, 6),
('Anna K.', 'Amsterdam, Netherlands', NULL, 'Words cannot fully capture the transformation I experienced. This work goes beyond anything I have encountered in my years of spiritual seeking. Abhay holds a space that is both fierce and tender, exactly what deep healing requires.', 'This work goes beyond anything I have encountered.', 'Training Program', 5, false, 7),
('Michael R.', 'Berlin, Germany', NULL, 'The Ancestral Fire Retreat was one of the most profound experiences of my life. I arrived carrying heavy ancestral patterns and left feeling lighter, clearer, and more connected to my lineage than ever before.', 'I arrived carrying heavy patterns and left feeling lighter.', 'Retreat', 5, false, 8),
('Thomas W.', 'Vienna, Austria', NULL, 'I was initially hesitant about online ceremony, but the Opening the Ancestral Channel session was incredibly powerful. I felt the energy transmission across the screen. Within days, my dreams intensified and old patterns began to surface for release.', 'The energy transmission was palpable even through the screen.', 'Online Ceremony', 5, true, 9);

-- GALLERY IMAGES
INSERT INTO gallery (title, description, image_url, category, display_order, is_active) VALUES
('Fire Ceremony', 'Sacred fire ceremony in the Altai Mountains', '/sao-gallery-img1.jpg', 'ceremony', 1, true),
('Sacred Landscape', 'The majestic Altai Mountains', '/sao-gallery-img2.jpg', 'nature', 2, true),
('Mountain Retreat', 'Group photo from the mountain retreat', '/sao-gallery-img3.jpg', 'retreat', 3, true),
('Drum Circle', 'Evening drum circle around the fire', '/sao-gallery-img4.jpg', 'ceremony', 4, true),
('Journey Within', 'Participant in deep journey state', '/sao-gallery-img5.jpg', 'portrait', 5, true),
('Altai Mountains', 'Sacred landscape of Siberia', '/sao-gallery-img6.jpg', 'travel', 6, true),
('Sacred Tree', 'Ancient cedar tree ceremony site', '/sao-gallery-img7.jpg', 'nature', 7, true),
('Healing Circle', 'Group healing ceremony', '/sao-gallery-img8.jpg', 'ceremony', 8, true),
('The Shaman', 'Abhay Oyun in ceremonial dress', '/sao-gallery-img9.jpg', 'portrait', 9, true),
('Abhay Oyun Portrait', 'Master Shaman Abhay Oyun', '/abhay_img.png', 'portrait', 10, true),
('Birch Forest', 'Sacred birch forest ceremony site', '/shaman_birch_forest.png', 'nature', 11, true),
('Sacred Fire', 'Night fire ceremony', '/shaman_fire.png', 'ceremony', 12, true);

-- TEACHINGS
INSERT INTO teachings (title, slug, excerpt, content, category, featured_image, status, is_featured, read_time_minutes) VALUES
('What Happens When the Drum Stops', 'what-happens-when-drum-stops', 'On silence, integration, and the work that happens after ceremony. The most profound transformations often occur in the days and weeks following a sacred ritual.', 'Most people are prepared for the ceremony itself. Few are prepared for what comes after — the dreams that shift, the emotions that surface, the memories that return. This is the sacred work of integration. When the drum stops, the real journey begins. The silence that follows ceremony is not empty; it is full of potential. In that space, the seeds planted during our work together begin to germinate. This is why we place such emphasis on post-ceremony integration at our retreats.', 'ceremony', '/shaman_drum.png', 'published', true, 15),
('On Choosing a Shaman', 'on-choosing-a-shaman', 'How to find the right practitioner for your journey. What questions to ask, what signs to look for, and how to trust your intuition.', 'Choosing a shamanic practitioner is one of the most important decisions you will make on your healing journey. Look for lineage, authenticity, and the feeling of being truly seen. A real shaman does not need to convince you — their presence will do the talking.', 'guide', '/abhay_img.png', 'published', false, 6),
('The Difference Between Healing and Fixing', 'healing-vs-fixing', 'Why transformation cannot be rushed, and the crucial distinction between quick fixes and deep healing.', 'In the modern world, we are conditioned to seek quick fixes. A pill for every problem, a technique for every challenge. But healing is not fixing. Fixing addresses symptoms; healing addresses the root. Fixing returns you to baseline; healing elevates you to a new level of being.', 'philosophy', '/sampo_gold_shield.png', 'published', false, 8);

-- CONTACTS (sample leads)
INSERT INTO contacts (name, email, phone, subject, message, source, status, priority) VALUES
('Maria Santos', 'maria.santos@email.com', '+31 6 12345678', 'Ancestral Fire Retreat Inquiry', 'I am deeply drawn to participate in the Ancestral Fire Retreat. I have been on a spiritual journey for several years and feel called to work with fire and ancestral healing.', 'begin_journey', 'new', 'high'),
('James Chen', 'james.chen@email.com', NULL, 'Plant Medicine Integration', 'Looking for guidance on integrating my recent plant medicine experience. I had a profound journey three weeks ago and need professional support.', 'contact_form', 'contacted', 'medium'),
('Sofia Andersson', 'sofia.a@email.com', '+46 7 12345678', 'Level 2 Training', 'I completed the Level 1 Shamanic Training last year and feel ready for Level 2. Please send information about the next program.', 'contact_form', 'converted', 'low');

-- NEWSLETTER SUBSCRIPTIONS
INSERT INTO newsletter_subscriptions (email, name, source, status) VALUES
('elena@example.com', 'Elena', 'website', 'active'),
('marcus@example.com', 'Marcus', 'website', 'active'),
('sarah@example.com', 'Sarah', 'retreat', 'active');
